#!/usr/bin/env python3

import argparse
import csv
import html
import re
import urllib.request
from pathlib import Path
from urllib.parse import urljoin


ENTRY_RE = re.compile(
    r'<dt class="ptitle"><br><a href="([^"]+)">(.*?)</a></dt>\s*'
    r"<dd>(.*?)</dd>\s*<dd>(.*?)</dd>",
    flags=re.S,
)


def normalize_space(value: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(value)).strip()


def fetch_url(url: str) -> str:
    with urllib.request.urlopen(url) as response:
        return response.read().decode("utf-8", errors="replace")


def write_csv(path: Path, fieldnames, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def parse_entries(proceedings_url: str, toc_html: str):
    entries = []
    for href, raw_title, authors_html, links_html in ENTRY_RE.findall(toc_html):
        title = normalize_space(raw_title)
        author_names = [normalize_space(name) for name in re.findall(r'value="([^"]+)"', authors_html)]
        pdf_match = re.search(r'href="([^"]+_paper\.pdf)"', links_html)
        pdf_url = urljoin(proceedings_url, pdf_match.group(1)) if pdf_match else ""
        entries.append(
            {
                "paper_page_url": urljoin(proceedings_url, href),
                "pdf_url": pdf_url,
                "title": title,
                "author_names": author_names,
            }
        )
    return entries


def build_rows(entries, conference: str, year: int):
    papers = []
    paper_authors = []
    authors = []
    paper_index = []
    author_counter = 1

    for paper_counter, entry in enumerate(entries, start=1):
        paper_id = f"{conference.upper()}-{year}-P{paper_counter:04d}"
        author_ids = []
        for position, author_name in enumerate(entry["author_names"], start=1):
            author_id = f"{conference.upper()}-{year}-A{author_counter:06d}"
            author_counter += 1
            author_ids.append(author_id)
            authors.append(
                {
                    "author_id": author_id,
                    "author_name": author_name,
                    "country": "UNKNOWN",
                    "institution": "UNKNOWN",
                    "conference": conference,
                    "year": str(year),
                    "source_url": entry["paper_page_url"],
                    "source_note": "Parsed from proceedings page; affiliation enrichment pending from PDF or other raw sources",
                }
            )
            paper_authors.append(
                {
                    "paper_id": paper_id,
                    "author_id": author_id,
                    "author_position": str(position),
                }
            )

        papers.append(
            {
                "paper_id": paper_id,
                "title": entry["title"],
                "author_ids": "|".join(author_ids),
                "conference": conference,
                "year": str(year),
                "source_url": entry["paper_page_url"],
            }
        )
        paper_index.append(
            {
                "paper_id": paper_id,
                "title": entry["title"],
                "paper_page_url": entry["paper_page_url"],
                "pdf_url": entry["pdf_url"],
            }
        )

    return authors, papers, paper_authors, paper_index


def write_collection_notes(path: Path, conference: str, year: int, proceedings_url: str, paper_count: int, author_count: int):
    text = f"""# {conference} {year} Collection Notes

- Conference: {conference}
- Year: {year}
- Proceedings URL: {proceedings_url}
- Collection status: script-generated proceedings metadata

## Scope

This dataset was generated by `scripts/collect_cvf_openaccess.py`.

Included in this run:

- full proceedings table of contents parsing from the CVF open access page
- all paper titles from the proceedings page
- ordered author lists from the proceedings page
- paper page URLs and PDF URLs in the raw index

Not yet included:

- institution and country enrichment from paper PDFs or other metadata sources

## Counts

- Papers collected: {paper_count}
- Author records collected: {author_count}

## Notes

- `authors.csv` currently uses `UNKNOWN` for `institution` and `country` until a raw-first-page extraction or later enrichment pass is performed.
- `papers_index.csv` contains the paper and PDF URLs needed by downstream raw-data retrieval scripts.
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Collect CVF Open Access proceedings metadata into normalized CSVs.")
    parser.add_argument("--conference", required=True)
    parser.add_argument("--conference-slug", required=True)
    parser.add_argument("--year", required=True, type=int)
    parser.add_argument("--proceedings-url", required=True)
    parser.add_argument("--raw-dir", required=True)
    parser.add_argument("--normalized-dir", required=True)
    parser.add_argument("--toc-html", help="Use an existing local proceedings HTML file instead of downloading.")
    args = parser.parse_args()

    raw_dir = Path(args.raw_dir)
    normalized_dir = Path(args.normalized_dir)
    raw_dir.mkdir(parents=True, exist_ok=True)
    normalized_dir.mkdir(parents=True, exist_ok=True)

    if args.toc_html:
        toc_path = Path(args.toc_html)
        toc_html = toc_path.read_text(encoding="utf-8")
    else:
        toc_html = fetch_url(args.proceedings_url)
        toc_path = raw_dir / "toc.html"
        toc_path.write_text(toc_html, encoding="utf-8")

    entries = parse_entries(args.proceedings_url, toc_html)
    authors, papers, paper_authors, paper_index = build_rows(entries, args.conference, args.year)

    write_csv(
        normalized_dir / "authors.csv",
        ["author_id", "author_name", "country", "institution", "conference", "year", "source_url", "source_note"],
        authors,
    )
    write_csv(
        normalized_dir / "papers.csv",
        ["paper_id", "title", "author_ids", "conference", "year", "source_url"],
        papers,
    )
    write_csv(
        normalized_dir / "paper_authors.csv",
        ["paper_id", "author_id", "author_position"],
        paper_authors,
    )
    write_csv(
        raw_dir / "papers_index.csv",
        ["paper_id", "title", "paper_page_url", "pdf_url"],
        paper_index,
    )
    write_csv(
        raw_dir / "source_manifest.csv",
        ["source_url", "source_type", "used_for", "notes"],
        [
            {
                "source_url": args.proceedings_url,
                "source_type": "proceedings_landing_page",
                "used_for": "full table of contents, titles, and author order",
                "notes": "Primary source for CVF Open Access proceedings metadata",
            }
        ],
    )
    write_collection_notes(
        raw_dir / "collection_notes.md",
        args.conference,
        args.year,
        args.proceedings_url,
        len(papers),
        len(authors),
    )

    print(f"Collected {len(papers)} papers and {len(authors)} author records")


if __name__ == "__main__":
    main()
