#!/usr/bin/env python3

import argparse
import csv
import html
import re
import subprocess
from pathlib import Path
from urllib.parse import urljoin


USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/123.0.0.0 Safari/537.36"
)
PAPER_BLOCK_RE = re.compile(r'<div class="paper">(.*?)</div>', flags=re.S)


def normalize_space(value: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(value)).strip()


def fetch_url(url: str) -> str:
    result = subprocess.run(
        ["curl", "-L", "--fail", "--silent", "-A", USER_AGENT, url],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout


def write_csv(path: Path, fieldnames, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def parse_entries(proceedings_url: str, toc_html: str):
    entries = []
    for block in PAPER_BLOCK_RE.findall(toc_html):
        title_match = re.search(r'<p class="title">(.*?)</p>', block, flags=re.S)
        authors_match = re.search(r'<span class="authors">(.*?)</span>', block, flags=re.S)
        abs_match = re.search(r'\[<a href="([^"]+)">abs</a>\]', block)
        pdf_match = re.search(r'\[<a href="([^"]+)"[^>]*>Download PDF</a>\]', block)
        if not title_match or not authors_match or not abs_match:
            continue

        authors_text = normalize_space(authors_match.group(1)).replace(", ", ",")
        author_names = [
            normalize_space(part)
            for part in authors_text.split(",")
            if normalize_space(part)
        ]
        entries.append(
            {
                "paper_page_url": urljoin(proceedings_url, abs_match.group(1)),
                "pdf_url": urljoin(proceedings_url, pdf_match.group(1)) if pdf_match else "",
                "title": normalize_space(title_match.group(1)),
                "author_names": author_names,
            }
        )
    return entries


def build_rows(entries, conference: str, year: int):
    papers = []
    paper_authors = []
    authors = []
    paper_index = []
    author_counter = 1

    for paper_counter, entry in enumerate(entries, start=1):
        paper_id = f"{conference.upper()}-{year}-P{paper_counter:04d}"
        author_ids = []
        for position, author_name in enumerate(entry["author_names"], start=1):
            author_id = f"{conference.upper()}-{year}-A{author_counter:06d}"
            author_counter += 1
            author_ids.append(author_id)
            authors.append(
                {
                    "author_id": author_id,
                    "author_name": author_name,
                    "country": "UNKNOWN",
                    "institution": "UNKNOWN",
                    "conference": conference,
                    "year": str(year),
                    "source_url": entry["paper_page_url"],
                    "source_note": "Parsed from PMLR proceedings page; affiliation enrichment pending from PDF first pages",
                }
            )
            paper_authors.append(
                {
                    "paper_id": paper_id,
                    "author_id": author_id,
                    "author_position": str(position),
                }
            )

        papers.append(
            {
                "paper_id": paper_id,
                "title": entry["title"],
                "author_ids": "|".join(author_ids),
                "conference": conference,
                "year": str(year),
                "source_url": entry["paper_page_url"],
            }
        )
        paper_index.append(
            {
                "paper_id": paper_id,
                "title": entry["title"],
                "paper_page_url": entry["paper_page_url"],
                "pdf_url": entry["pdf_url"],
            }
        )

    return authors, papers, paper_authors, paper_index


def write_collection_notes(path: Path, conference: str, year: int, proceedings_url: str, paper_count: int, author_count: int, paper_limit: int):
    scope_line = (
        f"- collection limited to the first {paper_limit} papers for workflow probing"
        if paper_limit
        else "- full proceedings page parsed"
    )
    text = f"""# {conference} {year} Collection Notes

- Conference: {conference}
- Year: {year}
- Proceedings URL: {proceedings_url}
- Collection status: script-generated proceedings metadata

## Scope

This dataset was generated by `scripts/collect_pmlr_proceedings.py`.

Included in this run:

{scope_line}
- paper titles and ordered author lists from the PMLR proceedings page
- abstract page URLs and PDF URLs in `papers_index.csv`

## Counts

- Papers collected: {paper_count}
- Author records collected: {author_count}
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Collect PMLR proceedings metadata into normalized CSVs.")
    parser.add_argument("--conference", required=True)
    parser.add_argument("--conference-slug", required=True)
    parser.add_argument("--year", required=True, type=int)
    parser.add_argument("--proceedings-url", required=True)
    parser.add_argument("--raw-dir", required=True)
    parser.add_argument("--normalized-dir", required=True)
    parser.add_argument("--paper-limit", type=int, default=0)
    args = parser.parse_args()

    raw_dir = Path(args.raw_dir)
    normalized_dir = Path(args.normalized_dir)
    raw_dir.mkdir(parents=True, exist_ok=True)
    normalized_dir.mkdir(parents=True, exist_ok=True)

    toc_html = fetch_url(args.proceedings_url)
    (raw_dir / "toc.html").write_text(toc_html, encoding="utf-8")

    entries = parse_entries(args.proceedings_url, toc_html)
    if args.paper_limit:
        entries = entries[: args.paper_limit]
    authors, papers, paper_authors, paper_index = build_rows(entries, args.conference, args.year)

    write_csv(
        normalized_dir / "authors.csv",
        ["author_id", "author_name", "country", "institution", "conference", "year", "source_url", "source_note"],
        authors,
    )
    write_csv(
        normalized_dir / "papers.csv",
        ["paper_id", "title", "author_ids", "conference", "year", "source_url"],
        papers,
    )
    write_csv(
        normalized_dir / "paper_authors.csv",
        ["paper_id", "author_id", "author_position"],
        paper_authors,
    )
    write_csv(
        raw_dir / "papers_index.csv",
        ["paper_id", "title", "paper_page_url", "pdf_url"],
        paper_index,
    )
    write_csv(
        raw_dir / "source_manifest.csv",
        ["source_url", "source_type", "used_for", "notes"],
        [
            {
                "source_url": args.proceedings_url,
                "source_type": "pmlr_proceedings_page",
                "used_for": "paper titles, author order, abstract URLs, PDF URLs",
                "notes": "Primary source for ICML proceedings metadata",
            }
        ],
    )
    write_collection_notes(
        raw_dir / "collection_notes.md",
        args.conference,
        args.year,
        args.proceedings_url,
        len(papers),
        len(authors),
        args.paper_limit,
    )

    print(f"Collected {len(papers)} papers and {len(authors)} author records")


if __name__ == "__main__":
    main()
